// <auto-generated />
using System;
using BookRadar.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookRadar.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BookRadarDbContext))]
    [Migration("20250812060216_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookRadar.Infrastructure.Persistence.Entities.SearchHistoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Autor");

                    b.Property<int?>("PublicationYear")
                        .HasColumnType("int")
                        .HasColumnName("AnioPublicacion");

                    b.Property<string>("Publisher")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Editorial");

                    b.Property<DateTime>("SearchedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaConsulta");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("Titulo");

                    b.HasKey("Id");

                    b.HasIndex("Author", "Title", "SearchedAt");

                    b.ToTable("HistorialBusquedas", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
